spring.application.name=WhatsAppAssistant
server.port=${PORT:8080}

whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}

gemini.api-key=${GEMINI_API_KEY}

composio.api-key=${COMPOSIO_API_KEY}
composio.gmail-auth-config-id=${COMPOSIO_GMAIL_AUTH_CONFIG_ID}
composio.google-calendar-auth-config-id=${COMPOSIO_GOOGLE_CALENDAR_AUTH_CONFIG_ID}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
